"""HAM: UMI deduplication and MEX matrix generation."""

import os
import gzip
import time
import numpy as np
import scipy.sparse
from collections import defaultdict, Counter

from .encoding import decode_umi


def dedup_umis_directional(umi_list: list, threshold: int = 1) -> int:
    """Hash-accelerated directional UMI dedup (UMI-tools algorithm).

    Mathematically identical to UMI-tools directional.
    Replaces O(n x m) linear scan with O(n x 36) hash operations
    (12 bp UMI × 3 alternative bases).

    Returns number of retained UMIs after deduplication.
    """
    if not umi_list:
        return 0

    umi_counts = Counter(umi_list)
    sorted_umis = sorted(umi_counts.keys(), key=lambda u: -umi_counts[u])

    local_hash: dict[str, str] = {}
    retained_count = 0

    for umi in sorted_umis:
        if umi in local_hash:
            continue

        retained_count += 1
        if umi not in local_hash:
            local_hash[umi] = umi

        if threshold >= 1:
            for pos in range(len(umi)):
                orig = umi[pos]
                for alt in ('A', 'C', 'G', 'T'):
                    if alt == orig:
                        continue
                    variant = umi[:pos] + alt + umi[pos + 1:]
                    if variant not in local_hash:
                        local_hash[variant] = umi

    return retained_count


def build_count_matrix(hits_path: str, output_dir: str,
                       umi_threshold: int = 1):
    """Build deduplicated count matrix from hits.npz.

    Input: hits.npz (binary numpy format)
      - hits: (N, 3) int32 — [cb_idx, umi_int, guide_idx]
      - barcode_list: (M,) str — index -> barcode string
      - idx_to_id: (K,) str — index -> guide ID string

    Output: MEX trio (matrix.mtx.gz, barcodes.tsv.gz, features.tsv.gz)
    """
    t0 = time.time()

    # ── 1. Load hits.npz ──
    print("[1/3] Loading hits.npz...")
    data = np.load(hits_path, allow_pickle=True)
    hits = data['hits']
    barcode_list = list(data['barcode_list'])
    idx_to_id = list(data['idx_to_id'])
    data.close()

    total_hits = len(hits)
    print(f"  Loaded {total_hits:,} hits")

    # ── 2. Group UMIs by (CB, guide) + UMI dedup ──
    print(f"[2/3] Grouping UMIs + deduplication (directional, threshold={umi_threshold})...")
    cb_guide_umis: dict[tuple, list] = defaultdict(list)

    for row in hits:
        cb_idx, umi_int, guide_idx = int(row[0]), int(row[1]), int(row[2])
        cb_guide_umis[(cb_idx, guide_idx)].append(umi_int)

    unique_pairs = len(cb_guide_umis)
    print(f"  Unique (CB, guide) pairs: {unique_pairs:,}")

    cb_guide_count: dict[tuple, int] = {}
    total_raw_umis = 0
    total_dedup_umis = 0

    for (cb_idx, guide_idx), umi_ints in cb_guide_umis.items():
        umi_strs = [decode_umi(u) for u in umi_ints]
        raw = len(umi_strs)
        dedup = dedup_umis_directional(umi_strs, umi_threshold)
        if dedup > 0:
            cb_guide_count[(cb_idx, guide_idx)] = dedup
        total_raw_umis += raw
        total_dedup_umis += dedup

    print(f"  Raw UMIs: {total_raw_umis:,}")
    pct = total_dedup_umis / max(total_raw_umis, 1) * 100
    print(f"  After dedup: {total_dedup_umis:,} ({pct:.1f}%)")

    # ── 3. Build sparse matrix + write MEX ──
    print("[3/3] Building matrix + writing MEX...")
    used_cb_indices = sorted(set(cb for cb, _ in cb_guide_count.keys()))
    used_guide_indices = sorted(set(gid for _, gid in cb_guide_count.keys()))

    cb_idx_to_pos = {cb: i for i, cb in enumerate(used_cb_indices)}
    guide_idx_to_pos = {gid: i for i, gid in enumerate(used_guide_indices)}

    rows, cols, data_vals = [], [], []
    for (cb_idx, guide_idx), count in cb_guide_count.items():
        rows.append(cb_idx_to_pos[cb_idx])
        cols.append(guide_idx_to_pos[guide_idx])
        data_vals.append(count)

    matrix = scipy.sparse.csr_matrix(
        (data_vals, (rows, cols)),
        shape=(len(used_cb_indices), len(used_guide_indices)),
        dtype=np.int32,
    )

    os.makedirs(output_dir, exist_ok=True)
    used_barcodes = [barcode_list[i] for i in used_cb_indices]
    used_features = [idx_to_id[i] for i in used_guide_indices]

    mtx_path = os.path.join(output_dir, 'matrix.mtx.gz')
    with gzip.open(mtx_path, 'wt') as f:
        f.write("%%MatrixMarket matrix coordinate integer general\n")
        f.write("% Generated by HAM\n")
        f.write(f"{matrix.shape[0]} {matrix.shape[1]} {matrix.nnz}\n")
        coo = matrix.tocoo()
        for r, c, v in zip(coo.row, coo.col, coo.data):
            f.write(f"{r + 1} {c + 1} {v}\n")

    bc_path = os.path.join(output_dir, 'barcodes.tsv.gz')
    with gzip.open(bc_path, 'wt') as f:
        for bc in used_barcodes:
            f.write(f"{bc}\n")

    ft_path = os.path.join(output_dir, 'features.tsv.gz')
    with gzip.open(ft_path, 'wt') as f:
        for ft in used_features:
            f.write(f"{ft}\t{ft}\tGuide\n")

    elapsed = time.time() - t0
    umi_per_cell = np.array(matrix.sum(axis=1)).flatten()
    nonzero_cells = (umi_per_cell > 0).sum()

    print(f"\n{'='*60}")
    print("MATRIX GENERATION COMPLETE (HAM)")
    print(f"{'='*60}")
    print(f"  Cells (barcodes):    {len(used_barcodes):>10,}")
    print(f"  Features (guides):   {len(used_features):>10,}")
    print(f"  Non-zero entries:    {matrix.nnz:>10,}")
    print(f"  Cells with >0 UMI:   {nonzero_cells:>10,}")
    print(f"  Total UMIs:          {int(matrix.sum()):>10,}")
    if nonzero_cells > 0:
        print(f"  Median UMI/cell:     "
              f"{np.median(umi_per_cell[umi_per_cell > 0]):>10.1f}")
    print(f"  Time: {elapsed:.1f}s")
    print(f"  Output: {output_dir}/")
    print(f"{'='*60}")
